### ISSUE TITLE
src/__pycache__ should not be in repository

### ISSUE THREAD

**Issue by gmacario** [Istorn/Audio2Text-Telegram-Chatbot#1]
I believe that <https://github.com/Istorn/Audio2Text-Telegram-Chatbot/tree/main/src/__pycache__> should be removed from the git repository.

In general I would remove all the `*.pyc` files from the repository, and add a toplevel `.gitignore` to avoid checking in those files again in the future

**Comment by Istorn** [comment]
Hello @gmacario and thanks for your support.

You're totally right: I missed out some additional directives into the `.gitignore` files, which has been right now updated.
